### ISSUE TITLE
writing custom css

### ISSUE THREAD

**Issue by afidegnum** [justgage/tachyons-elm#20]
is there a way to modify or write my own css classes on top of this? 

i hope this package gets maintained for a long period of time

**Comment by justgage** [comment]
Tachyons is just a CSS library, so you can just include any CSS file in your HTML. Also you could modify Tachyons itself and include it. Just don't do `tachyons.css` in your elm code. 

I haven't maintained it greatly, but also, it doesn't need much maintenance because the elm files are generated from the Tachyons file automatically and the Tachyons doesn't change very rapidly. 

Tell me if that answers your question :)

**Comment by afidegnum** [comment]
Thanks a lot, i have noticed the css file which can be generated, i can chip in my css-rule there as well, 

but i Open a new issue related to SVG, i think there is an interference.

**Comment by justgage** [comment]
Ok sounds good 👍
