### ISSUE TITLE
generate css classes with your ./build.sh

### ISSUE THREAD

**Issue by afidegnum** [justgage/tachyons-elm#22]
is it possible we can generate other css files as well with your convert.js and class extractor script? 

I come accross other html templates but have difficulty using them in elm but looking at the script used to convert tachyon.css could have similar applications to other css files as well.

**Comment by justgage** [comment]
It's reasonably general purpose. Given some more exotic use-cases it might fall down but try it! I would love for it to someday become a standalone thing. I know that this package used my script as a jumping off point for tailwind: https://package.elm-lang.org/packages/splodingsocks/elm-tailwind/2.2.1/

**Comment by afidegnum** [comment]
Hi, Thanks for your insight, Can you please look into this? i couldn't have a full generated css structures. 

I m trying with a bulma css class `https://github.com/jgthms/bulma/blob/master/css/bulma.css`

but some classes are left out, i dont' know why. 

is there a way to convert the whole CSS class to an mdgriffith/style-elements/  or `rtfeldman/elm-css/` i believe with this, we can only use the needed css classes whch will as well enhance the performance. 

What do you think?

**Comment by justgage** [comment]
Hm... odd. Honestly I'm not super familiar with the code there is some logic that exists in the javascript file. It's been a long time. I would just `console.log` to see the full rules and figure out why they aren't getting output. 

CSS-in-Elm solutions are great if you don't care about caching. They ship less CSS, but you can't cache it across pages. One of the coolest things about tachyons/tailwind/any functional CSS framework is the fact that you can cache them for long periods of time due to the slow nature of them changing.

However it's an interesting idea that I think a lot of people that are trying to convert old codebases to could benefit from. It also tends to be a lot better for Elm libraries because you don't have to instruct people to include CSS files themselves.

**Comment by afidegnum** [comment]
thanks a lot for the insight,

for the mean time i m trying to fix the bug and also use the traditional method of adding the css file to the html file and use the needed classes. I will also try to purge unused css as well,

**Comment by justgage** [comment]
Sounds good, good luck 🤞😄
